const data = {
    products: [
        { 
            name: 'Nike Slim shirts',
            slug: 'nike-slim-shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numRevies: 10,
            descriptions: 'high quality shirts',
        },
        { 
            name: 'Adidas Fit shirts',
            slug: 'adidas-fit-shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 250,
            countStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numRevies: 10,
            descriptions: 'high quality product',
        },
        { 
            name: 'Nike Slim Pants',
            slug: 'nike-slim-pants',
            category: 'Pants',
            image: '/images/p3.jpg',
            price: 25,
            countStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numRevies: 14,
            descriptions: 'high quality products',
        },
        { 
            name: 'Adidas Fit Pants',
            slug: 'Adidas-Fit-pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 65,
            countStock: 5,
            brand: 'Puma',
            rating: 4.5,
            numRevies: 10,
            descriptions: 'high quality products',
        },
    ],
};
export default data;